# Połączenie z kontenerem PostgreSQL
spring.datasource.url=jdbc:postgresql://baza-treningowa:5432/dziennik
spring.datasource.username=admin
spring.datasource.password=superhaslo123

# Spring sam stworzy tabele dla Treningów i Użytkowników
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect